basic UI
Obimbo07/school-library pull request #4
Opened 2023-12-08 18:14 UTC by Obimbo07

In this PR the following changes were implemented:

- Create a app.rb file that will serve as your console app entry-point. It should have methods that do the following:

List all books.
List all people.
Create a person (teacher or student, not a plain Person).
Create a book.
Create a rental.
List all rentals for a given person id.

- In your main.rb define the entry point, this will be a method called main that is invoked at the end of your file. This method should do the following:

Present the user with a list of options to perform.
Lets users choose an option.
If needed, ask for parameters for the option.
Have a way to quit the app.

2023-12-08 18:35 UTC, danmainah requested changes
Hi @Obimbo07 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️  Implemented the App class that has the functionality to add new persons and list persons add books and list books, add rentals, and list rentals.
✔️  Added entry point for the app in main.rb file with a method to list options.


# Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-12-08 18:35 UTC, danmainah commented on main.rb
> +end
- [ ] @Obimbo07 Great work adding the UI, however, the UI doesn't get displayed in the console, kindly check your implementation of the prompts, if using a method you should call them for the UI to get displayed( in your case you can call prompt method to display the menu list).

- [ ] After implementing the changes requested kindly ensure the UI matches the design given from the sneak peek video and all menu options should work correctly.

2023-12-08 19:54 UTC, Ghiftee requested changes
## STATUS: CHANGES REQUIRED ♻️♻️
Hi there @Obimbo07 👋🏽 , 

Great work on making the changes requested by a previous reviewer 👏 
To highlight 👍🏽 
✔️ The Ui is displayed in the console
✔️ A book can be created successfully
✔️ No linter errors
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExdTZlYXJxaTQ4aGExOTFoNHEzZWhkam15YW1hY2wyeG56d2gycHd0aSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/YT95XJOLvY1t2SJgpR/giphy.gif)

 ## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-12-08 19:54 UTC, Ghiftee commented on main.rb
> +  when 3
- [ ] Great job working on the project thus far! However, when I try to create a `student` or `teacher`, I get this error and cannot successfully create a person or test a rental.
<img width="1124" alt="Screenshot 2023-12-08 at 20 47 57" src="https://github.com/Obimbo07/school-library/assets/64774936/10bb6537-d1b8-454b-ba8d-ed9dc3d3c4fe">

2023-12-09 07:09 UTC, 1GORDON approved these changes
# Status: APPROVED 🟢 

Hi @Obimbo07 ✋

Your project is complete!  There is nothing else to say other than... it's time to merge it: ship it:
Congratulations! :tada: :clap: :clap: :100:

## Highlights!
- Implemented requested changes ✔️
- UI works as expected ✔️

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend considering them as they can improve your code._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@1GORDON` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-12-11 13:48 UTC, merged